In [1]:
def import_data(filename):
	data_df= pd.read_csv(filename)
	return data_df

In [4]:
import numpy as np
import pandas as pd

In [5]:
filename = "evaluation_data.csv"

In [6]:
df = import_data(filename)

In [8]:
df.iloc[3].term

' 36 months'

In [12]:
df.iloc[:5,:10]

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership
0,90531864,4500,36 months,12.79%,151.17,C,C1,NaN,n/a,MORTGAGE
1,90521796,25000,60 months,14.49%,588.08,C,C4,USA,10+ years,MORTGAGE
2,90270660,2000,36 months,13.49%,67.87,C,C2,Training & Education Manager,1 year,MORTGAGE
3,90611738,20000,36 months,8.99%,635.91,B,B1,NaN,n/a,MORTGAGE
4,90692987,35000,60 months,15.59%,843.53,C,C5,Vice president of culinary,1 year,MORTGAGE

In [14]:
df=df.dropna(axis=1)

In [16]:
df=df.drop("emp_length", axis=1)

In [17]:
df

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,home_ownership,annual_inc,verification_status,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,is_good_customer
0,90531864,4500,36 months,12.79%,151.17,C,C1,MORTGAGE,56000.0,Verified,...,0,5,89.5,1,0,172519,42279,25500,44819,yes
1,90521796,25000,60 months,14.49%,588.08,C,C4,MORTGAGE,100000.0,Not Verified,...,0,4,97.1,0,0,273664,46051,5000,68764,yes
2,90270660,2000,36 months,13.49%,67.87,C,C2,MORTGAGE,80000.0,Source Verified,...,0,5,85.7,0,0,356823,47580,2500,59315,yes
3,90611738,20000,36 months,8.99%,635.91,B,B1,MORTGAGE,76332.0,Not Verified,...,0,3,95.7,0,0,405800,27906,51000,10000,yes
4,90692987,35000,60 months,15.59%,843.53,C,C5,MORTGAGE,220000.0,Source Verified,...,0,3,92.3,0,0,673762,66494,118400,46682,yes
5,90211258,14850,60 months,18.99%,385.14,D,D3,MORTGAGE,65000.0,Verified,...,0,4,95.0,0,0,82766,9112,8000,0,no
6,90191117,2000,36 months,18.99%,73.31,D,D3,RENT,34000.0,Verified,...,0,2,90.9,0,0,15500,9163,5500,4000,yes
7,90611716,4000,36 months,10.99%,130.94,B,B4,MORTGAGE,60000.0,Verified,...,0,3,87.0,0,0,80539,44950,18400,19290,yes
8,90280064,1800,36 months,14.49%,61.95,C,C4,MORTGAGE,56000.0,Source Verified,...,0,2,100.0,0,0,207056,60953,10300,62446,yes
9,90591281,4800,36 months,15.59%,167.79,C,C5,OWN,47200.0,Source Verified,...,0,4,100.0,0,0,38645,26507,3600,22745,yes
10,90108929,3000,36 months,13.99%,102.52,C,C3,MORTGAGE,40000.0,Source Verified,...,1,0,66.7,0,0,221247,1401,500,0,no
11,90631697,10000,36 months,7.59%,311.48,A,A3,OWN,185000.0,Source Verified,...,0,8,95.6,0,0,983707,363086,44500,184757,yes
12,89817247,15000,60 months,13.99%,348.95,C,C3,MORTGAGE,50000.0,Source Verified,...,0,2,100.0,0,0,27700,16407,21500,0,yes
13,90695712,3000,36 months,16.99%,106.95,D,D1,MORTGAGE,70000.0,Source Verified,...,0,1,95.7,0,0,374500,54617,11800,51500,yes
14,90379558,16000,60 months,13.99%,372.21,C,C3,MORTGAGE,75000.0,Not Verified,...,0,4,100.0,0,0,197466,73764,39400,55110,yes
15,90164623,8000,36 months,8.99%,254.37,B,B1,RENT,60000.0,Source Verified,...,0,2,100.0,0,0,59138,42837,21700,37438,yes
16,90312085,7000,36 months,7.99%,219.33,A,A4,MORTGAGE,60320.0,Not Verified,...,0,4,100.0,0,0,165949,40745,24000,43389,yes
17,90078228,6000,36 months,11.49%,197.83,B,B5,RENT,53364.0,Source Verified,...,0,4,100.0,0,0,244281,30446,83500,29351,yes
18,89837832,5400,36 months,10.49%,175.49,B,B3,RENT,82500.0,Verified,...,0,4,100.0,0,0,117593,46105,61300,56293,yes
19,90312543,15000,60 months,15.59%,361.52,C,C5,MORTGAGE,55000.0,Source Verified,...,0,4,100.0,0,0,60900,2740,39900,0,yes
20,90571484,20000,60 months,24.99%,586.91,E,E4,MORTGAGE,75195.0,Verified,...,0,4,91.7,0,0,125299,48515,17500,46399,yes
21,90611373,6500,36 months,11.49%,214.32,B,B5,MORTGAGE,58000.0,Source Verified,...,0,4,95.3,0,0,348569,88582,29500,65169,yes
22,90407033,8700,36 months,23.99%,341.29,E,E2,MORTGAGE,60694.4,Verified,...,0,3,80.0,0,0,87735,21062,6000,18535,yes
23,88855464,10000,36 months,11.49%,329.72,B,B5,MORTGAGE,49500.0,Source Verified,...,0,6,100.0,1,0,211498,47693,19600,41492,yes
24,90601237,1000,36 months,14.49%,34.42,C,C4,RENT,26688.0,Verified,...,0,4,100.0,0,0,69063,45042,19000,47662,yes
25,89935364,10000,36 months,13.49%,339.31,C,C2,MORTGAGE,77000.0,Source Verified,...,0,1,87.9,0,0,72484,58882,11100,61384,yes
26,90611298,20000,36 months,17.99%,722.95,D,D2,RENT,66600.0,Not Verified,...,0,1,93.3,1,0,39353,28316,13900,25453,yes
27,90211482,32700,36 months,17.99%,1182.02,D,D2,MORTGAGE,150000.0,Source Verified,...,0,2,95.7,0,0,102659,65612,0,64259,yes
28,90481163,8000,36 months,8.99%,254.37,B,B1,MORTGAGE,130000.0,Not Verified,...,0,4,97.6,0,0,334332,55382,32200,71482,yes
29,90439579,6000,36 months,10.49%,194.99,B,B3,RENT,54858.0,Not Verified,...,0,2,92.0,1,1,96820,64744,20500,71220,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6615,84141109,15000,36 months,10.99%,491.01,B,B4,MORTGAGE,86000.0,Verified,...,0,1,92.0,0,0,251900,6681,6600,3500,yes
6616,84052818,7000,36 months,8.99%,222.57,B,B1,OWN,35000.0,Not Verified,...,0,0,87.5,0,0,17300,7747,13700,3000,yes
6617,83971195,26000,36 months,18.99%,952.93,D,D3,MORTGAGE,82000.0,Verified,...,0,3,85.2,0,0,97300,51340,28600,56000,no
6618,83816483,15000,36 months,10.99%,491.01,B,B4,MORTGAGE,78000.0,Source Verified,...,1,4,97.7,0,0,304871,49608,49600,73271,yes
6619,84043233,22675,60 months,22.39%,631.30,E,E1,MORTGAGE,47266.0,Source Verified,...,0,6,100.0,0,0,93352,11601,17400,7500,yes
6620,84131326,12000,36 months,10.49%,389.98,B,B3,OWN,60000.0,Not Verified,...,0,4,100.0,0,0,73300,22881,52300,20000,yes
6621,84052247,9900,36 months,17.99%,357.86,D,D2,RENT,83556.0,Verified,...,0,2,95.8,0,0,52189,63152,5700,44689,yes
6622,83971255,4800,36 months,12.79%,161.25,C,C1,RENT,22680.0,Source Verified,...,0,0,100.0,0,0,25491,23299,8400,15591,no
6623,84080812,4000,36 months,8.99%,127.19,B,B1,MORTGAGE,64000.0,Source Verified,...,0,0,45.5,0,0,262093,3132,1800,0,yes
6624,80591476,40000,60 months,15.59%,964.03,C,C5,OWN,84252.0,Verified,...,0,1,95.8,0,0,260941,32159,36900,36635,yes
6625,84131021,10000,36 months,11.49%,329.72,B,B5,MORTGAGE,90000.0,Source Verified,...,0,2,68.7,0,0,58729,19054,5000,43029,yes
6626,84091298,15000,36 months,16.99%,534.72,D,D1,MORTGAGE,89000.0,Verified,...,2,5,75.0,1,0,171037,37942,24900,34937,yes
6627,83656253,11400,36 months,28.88%,476.99,G,G2,MORTGAGE,35000.0,Verified,...,0,8,100.0,0,0,12600,3176,8300,0,yes
6628,84112449,6000,36 months,10.49%,194.99,B,B3,MORTGAGE,60000.0,Source Verified,...,0,4,100.0,0,0,208826,40350,19500,33926,yes
6629,83970302,4800,36 months,10.99%,157.13,B,B4,RENT,42000.0,Source Verified,...,0,3,94.7,0,0,85153,60185,22600,56453,yes
6630,84052127,15000,36 months,10.49%,487.47,B,B3,RENT,80000.0,Source Verified,...,0,1,100.0,0,0,171641,55807,12800,57516,yes
6631,83850088,28000,60 months,28.88%,886.73,G,G2,MORTGAGE,63500.0,Source Verified,...,0,5,100.0,1,0,205283,66601,17300,52182,no
6632,84001968,8000,36 months,8.59%,252.88,A,A5,MORTGAGE,63000.0,Not Verified,...,0,3,100.0,0,1,283355,118669,15700,113655,yes
6633,16522872,32000,60 months,15.59%,771.23,C,C5,MORTGAGE,121800.0,Verified,...,0,0,96.0,0,0,332602,114063,62600,28857,no
6634,84031506,7000,36 months,8.99%,222.57,B,B1,RENT,154000.0,Source Verified,...,0,1,100.0,0,0,192286,103165,145900,44886,yes
6635,83941404,5600,36 months,8.99%,178.06,B,B1,RENT,140000.0,Source Verified,...,0,3,100.0,1,0,61698,22450,21200,34398,yes
6636,84061209,3000,36 months,21.49%,113.79,D,D5,MORTGAGE,155000.0,Verified,...,2,4,78.4,0,0,309885,41056,4100,52251,yes
6637,83910551,15000,36 months,9.49%,480.43,B,B2,MORTGAGE,67000.0,Source Verified,...,0,1,86.7,0,0,320344,98909,6100,87729,yes
6638,83786889,28000,60 months,9.49%,587.92,B,B2,MORTGAGE,124000.0,Source Verified,...,0,1,100.0,1,0,461526,16675,21800,24726,yes
6639,83900146,20000,36 months,8.59%,632.19,A,A5,RENT,260000.0,Source Verified,...,0,3,92.9,0,0,112871,51830,60900,47704,yes
6640,83860152,16625,36 months,16.99%,592.65,D,D1,OWN,39600.0,Verified,...,0,1,96.6,0,0,151752,13151,15100,6152,yes
6641,84070422,6025,36 months,10.99%,197.23,B,B4,RENT,55000.0,Source Verified,...,0,1,100.0,1,0,42936,23936,7400,28736,yes
6642,83737081,18000,60 months,10.49%,386.81,B,B3,MORTGAGE,117000.0,Not Verified,...,0,1,100.0,0,0,550125,34571,18300,38225,yes
6643,83101159,8625,36 months,23.99%,338.34,E,E2,OWN,27000.0,Verified,...,0,3,84.2,0,0,12600,6405,12100,0,no
6644,611704,34000,60 months,7.89%,687.61,A,A5,RENT,87500.0,Verified,...,0,7,100.0,0,0,603045,102966,103800,88579,yes

In [18]:
def export_data(df, filename):
	df.to_csv(filename, index=False, header=True)

In [19]:
export_data(df, "test.csv")

In [25]:
term_to_num = lambda x: int(x.replace(" months", ""))

In [29]:
df_new = df

In [30]:
df_new.term = list(map(term_to_num, list(df.term)))

In [36]:
def int_rate_to_num(df):
	f = lambda x: float(x.replace("%", ""))
	df.int_rate = list(map(f, list(df.int_rate)))
	return df

In [37]:
df_new = int_rate_to_num(df_new)

In [38]:
df_new.int_rate

0       12.79
1       14.49
2       13.49
3        8.99
4       15.59
5       18.99
6       18.99
7       10.99
8       14.49
9       15.59
10      13.99
11       7.59
12      13.99
13      16.99
14      13.99
15       8.99
16       7.99
17      11.49
18      10.49
19      15.59
20      24.99
21      11.49
22      23.99
23      11.49
24      14.49
25      13.49
26      17.99
27      17.99
28       8.99
29      10.49
        ...
6615    10.99
6616     8.99
6617    18.99
6618    10.99
6619    22.39
6620    10.49
6621    17.99
6622    12.79
6623     8.99
6624    15.59
6625    11.49
6626    16.99
6627    28.88
6628    10.49
6629    10.99
6630    10.49
6631    28.88
6632     8.59
6633    15.59
6634     8.99
6635     8.99
6636    21.49
6637     9.49
6638     9.49
6639     8.59
6640    16.99
6641    10.99
6642    10.49
6643    23.99
6644     7.89
Name: int_rate, dtype: float64

In [43]:
df_new.loc[:, ["id", "term", "grade"]]

            id  term grade
0     90531864    36     C
1     90521796    60     C
2     90270660    36     C
3     90611738    36     B
4     90692987    60     C
5     90211258    60     D
6     90191117    36     D
7     90611716    36     B
8     90280064    36     C
9     90591281    36     C
10    90108929    36     C
11    90631697    36     A
12    89817247    60     C
13    90695712    36     D
14    90379558    60     C
15    90164623    36     B
16    90312085    36     A
17    90078228    36     B
18    89837832    36     B
19    90312543    60     C
20    90571484    60     E
21    90611373    36     B
22    90407033    36     E
23    88855464    36     B
24    90601237    36     C
25    89935364    36     C
26    90611298    36     D
27    90211482    36     D
28    90481163    36     B
29    90439579    36     B
...        ...   ...   ...
6615  84141109    36     B
6616  84052818    36     B
6617  83971195    36     D
6618  83816483    36     B
6619  84043233    60     E
6620  84131326    36     B
6621  84052247    36     D
6622  83971255    36     C
6623  84080812    36     B
6624  80591476    60     C
6625  84131021    36     B
6626  84091298    36     D
6627  83656253    36     G
6628  84112449    36     B
6629  83970302    36     B
6630  84052127    36     B
6631  83850088    60     G
6632  84001968    36     A
6633  16522872    60     C
6634  84031506    36     B
6635  83941404    36     B
6636  84061209    36     D
6637  83910551    36     B
6638  83786889    60     B
6639  83900146    36     A
6640  83860152    36     D
6641  84070422    36     B
6642  83737081    60     B
6643  83101159    36     E
6644    611704    60     A

[6645 rows x 3 columns]

In [45]:
df_raw = import_data("evaluation_data.csv")

In [46]:
df_raw

,id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,...,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,is_good_customer
0,90531864,4500,36 months,12.79%,151.17,C,C1,NaN,n/a,MORTGAGE,...,5,89.5,0.0,1,0,172519,42279,25500,44819,yes
1,90521796,25000,60 months,14.49%,588.08,C,C4,USA,10+ years,MORTGAGE,...,4,97.1,0.0,0,0,273664,46051,5000,68764,yes
2,90270660,2000,36 months,13.49%,67.87,C,C2,Training & Education Manager,1 year,MORTGAGE,...,5,85.7,100.0,0,0,356823,47580,2500,59315,yes
3,90611738,20000,36 months,8.99%,635.91,B,B1,NaN,n/a,MORTGAGE,...,3,95.7,0.0,0,0,405800,27906,51000,10000,yes
4,90692987,35000,60 months,15.59%,843.53,C,C5,Vice president of culinary,1 year,MORTGAGE,...,3,92.3,14.3,0,0,673762,66494,118400,46682,yes
5,90211258,14850,60 months,18.99%,385.14,D,D3,truck driver,10+ years,MORTGAGE,...,4,95.0,66.7,0,0,82766,9112,8000,0,no
6,90191117,2000,36 months,18.99%,73.31,D,D3,boxing,5 years,RENT,...,2,90.9,0.0,0,0,15500,9163,5500,4000,yes
7,90611716,4000,36 months,10.99%,130.94,B,B4,Quality Tech,9 years,MORTGAGE,...,3,87.0,100.0,0,0,80539,44950,18400,19290,yes
8,90280064,1800,36 months,14.49%,61.95,C,C4,Shipping,5 years,MORTGAGE,...,2,100.0,33.3,0,0,207056,60953,10300,62446,yes
9,90591281,4800,36 months,15.59%,167.79,C,C5,care giver,8 years,OWN,...,4,100.0,0.0,0,0,38645,26507,3600,22745,yes
10,90108929,3000,36 months,13.99%,102.52,C,C3,Cook I,2 years,MORTGAGE,...,0,66.7,0.0,0,0,221247,1401,500,0,no
11,90631697,10000,36 months,7.59%,311.48,A,A3,ASAC,10+ years,OWN,...,8,95.6,0.0,0,0,983707,363086,44500,184757,yes
12,89817247,15000,60 months,13.99%,348.95,C,C3,senior multi line representative,10+ years,MORTGAGE,...,2,100.0,75.0,0,0,27700,16407,21500,0,yes
13,90695712,3000,36 months,16.99%,106.95,D,D1,Asst manager,10+ years,MORTGAGE,...,1,95.7,100.0,0,0,374500,54617,11800,51500,yes
14,90379558,16000,60 months,13.99%,372.21,C,C3,Foreman,9 years,MORTGAGE,...,4,100.0,25.0,0,0,197466,73764,39400,55110,yes
15,90164623,8000,36 months,8.99%,254.37,B,B1,Senior Consultant,2 years,RENT,...,2,100.0,0.0,0,0,59138,42837,21700,37438,yes
16,90312085,7000,36 months,7.99%,219.33,A,A4,Mechanical Designer,2 years,MORTGAGE,...,4,100.0,0.0,0,0,165949,40745,24000,43389,yes
17,90078228,6000,36 months,11.49%,197.83,B,B5,Business Analyst,7 years,RENT,...,4,100.0,0.0,0,0,244281,30446,83500,29351,yes
18,89837832,5400,36 months,10.49%,175.49,B,B3,Mgr,10+ years,RENT,...,4,100.0,0.0,0,0,117593,46105,61300,56293,yes
19,90312543,15000,60 months,15.59%,361.52,C,C5,Data Center Supervisor,10+ years,MORTGAGE,...,4,100.0,0.0,0,0,60900,2740,39900,0,yes
20,90571484,20000,60 months,24.99%,586.91,E,E4,Paralegal,10+ years,MORTGAGE,...,4,91.7,66.7,0,0,125299,48515,17500,46399,yes
21,90611373,6500,36 months,11.49%,214.32,B,B5,International Sales Representative,8 years,MORTGAGE,...,4,95.3,25.0,0,0,348569,88582,29500,65169,yes
22,90407033,8700,36 months,23.99%,341.29,E,E2,SR ACCOUNTING ASSISTANT,9 years,MORTGAGE,...,3,80.0,50.0,0,0,87735,21062,6000,18535,yes
23,88855464,10000,36 months,11.49%,329.72,B,B5,Retwntions,< 1 year,MORTGAGE,...,6,100.0,37.5,1,0,211498,47693,19600,41492,yes
24,90601237,1000,36 months,14.49%,34.42,C,C4,Guest Reception Agent,1 year,RENT,...,4,100.0,0.0,0,0,69063,45042,19000,47662,yes
25,89935364,10000,36 months,13.49%,339.31,C,C2,Senior Engineer,< 1 year,MORTGAGE,...,1,87.9,100.0,0,0,72484,58882,11100,61384,yes
26,90611298,20000,36 months,17.99%,722.95,D,D2,supervisor,2 years,RENT,...,1,93.3,50.0,1,0,39353,28316,13900,25453,yes
27,90211482,32700,36 months,17.99%,1182.02,D,D2,Information Technology Specialist,9 years,MORTGAGE,...,2,95.7,NaN,0,0,102659,65612,0,64259,yes
28,90481163,8000,36 months,8.99%,254.37,B,B1,software developer/contractor at Vanguar,3 years,MORTGAGE,...,4,97.6,0.0,0,0,334332,55382,32200,71482,yes
29,90439579,6000,36 months,10.49%,194.99,B,B3,Regional Administrative Asst II,10+ years,RENT,...,2,92.0,0.0,1,1,96820,64744,20500,71220,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6615,84141109,15000,36 months,10.99%,491.01,B,B4,Program Specialist,10+ years,MORTGAGE,...,1,92.0,0.0,0,0,251900,6681,6600,3500,yes
6616,84052818,7000,36 months,8.99%,222.57,B,B1,Treatment plan coordinator,10+ years,OWN,...,0,87.5,0.0,0,0,17300,7747,13700,3000,yes
6617,83971195,26000,36 months,18.99%,952.93,D,D3,Director of Business & Administrative Se,10+ years,MORTGAGE,...,3,85.2,54.5,0,0,97300,51340,28600,56000,no
6618,83816483,15000,36 months,10.99%,491.01,B,B4,Territory Manager,6 years,MORTGAGE,...,4,97.7,0.0,0,0,304871,49608,49600,73271,yes
6619,84043233,22675,60 months,22.39%,631.30,E,E1,operations team member,10+ years,MORTGAGE,...,6,100.0,9.1,0,0,93352,11601,17400,7500,yes
6620,84131326,12000,36 months,10.49%,389.98,B,B3,Truck driver,8 years,OWN,...,4,100.0,0.0,0,0,73300,22881,52300,20000,yes
6621,84052247,9900,36 months,17.99%,357.86,D,D2,Project Manager,4 years,RENT,...,2,95.8,0.0,0,0,52189,63152,5700,44689,yes
6622,83971255,4800,36 months,12.79%,161.25,C,C1,Certified Nursing Assistant,1 year,RENT,...,0,100.0,100.0,0,0,25491,23299,8400,15591,no
6623,84080812,4000,36 months,8.99%,127.19,B,B1,Corp Tax Accounts Speacialist,10+ years,MORTGAGE,...,0,45.5,0.0,0,0,262093,3132,1800,0,yes
6624,80591476,40000,60 months,15.59%,964.03,C,C5,train dispatcher,4 years,OWN,...,1,95.8,0.0,0,0,260941,32159,36900,36635,yes
6625,84131021,10000,36 months,11.49%,329.72,B,B5,NaN,n/a,MORTGAGE,...,2,68.7,0.0,0,0,58729,19054,5000,43029,yes
6626,84091298,15000,36 months,16.99%,534.72,D,D1,Fire Fighter / Paramedic,10+ years,MORTGAGE,...,5,75.0,16.7,1,0,171037,37942,24900,34937,yes
6627,83656253,11400,36 months,28.88%,476.99,G,G2,NaN,n/a,MORTGAGE,...,8,100.0,0.0,0,0,12600,3176,8300,0,yes
6628,84112449,6000,36 months,10.49%,194.99,B,B3,Staff Services Analyst,8 years,MORTGAGE,...,4,100.0,40.0,0,0,208826,40350,19500,33926,yes
6629,83970302,4800,36 months,10.99%,157.13,B,B4,Coordinator Hotels,< 1 year,RENT,...,3,94.7,0.0,0,0,85153,60185,22600,56453,yes
6630,84052127,15000,36 months,10.49%,487.47,B,B3,Commercial Credit Specialist,5 years,RENT,...,1,100.0,50.0,0,0,171641,55807,12800,57516,yes
6631,83850088,28000,60 months,28.88%,886.73,G,G2,Postmaster,10+ years,MORTGAGE,...,5,100.0,55.6,1,0,205283,66601,17300,52182,no
6632,84001968,8000,36 months,8.59%,252.88,A,A5,Teacher,3 years,MORTGAGE,...,3,100.0,83.3,0,1,283355,118669,15700,113655,yes
6633,16522872,32000,60 months,15.59%,771.23,C,C5,Product Manager,9 years,MORTGAGE,...,0,96.0,57.1,0,0,332602,114063,62600,28857,no
6634,84031506,7000,36 months,8.99%,222.57,B,B1,Special Agent,10+ years,RENT,...,1,100.0,40.0,0,0,192286,103165,145900,44886,yes
6635,83941404,5600,36 months,8.99%,178.06,B,B1,Electrical Engineer,7 years,RENT,...,3,100.0,0.0,1,0,61698,22450,21200,34398,yes
6636,84061209,3000,36 months,21.49%,113.79,D,D5,AVP contracting,10+ years,MORTGAGE,...,4,78.4,40.0,0,0,309885,41056,4100,52251,yes
6637,83910551,15000,36 months,9.49%,480.43,B,B2,Senior Project Accountant,< 1 year,MORTGAGE,...,1,86.7,100.0,0,0,320344,98909,6100,87729,yes
6638,83786889,28000,60 months,9.49%,587.92,B,B2,SWITCHGEAR MANAGER,< 1 year,MORTGAGE,...,1,100.0,0.0,1,0,461526,16675,21800,24726,yes
6639,83900146,20000,36 months,8.59%,632.19,A,A5,Private Client Advisor,7 years,RENT,...,3,92.9,0.0,0,0,112871,51830,60900,47704,yes
6640,83860152,16625,36 months,16.99%,592.65,D,D1,NaN,n/a,OWN,...,1,96.6,0.0,0,0,151752,13151,15100,6152,yes
6641,84070422,6025,36 months,10.99%,197.23,B,B4,Claims Coordinator,1 year,RENT,...,1,100.0,50.0,1,0,42936,23936,7400,28736,yes
6642,83737081,18000,60 months,10.49%,386.81,B,B3,AVP Enterprise Service Manager,4 years,MORTGAGE,...,1,100.0,71.4,0,0,550125,34571,18300,38225,yes
6643,83101159,8625,36 months,23.99%,338.34,E,E2,NaN,n/a,OWN,...,3,84.2,40.0,0,0,12600,6405,12100,0,no
6644,611704,34000,60 months,7.89%,687.61,A,A5,Analyst,6 years,RENT,...,7,100.0,0.0,0,0,603045,102966,103800,88579,yes

In [51]:
df_raw.iloc[:, 7].name

'emp_title'

In [52]:
len(df_raw)

6645

In [69]:
del_rate = 0.5
df_new = df_raw
for i in range(len(df_raw.columns)):
    attr = list(df_raw.iloc[:, i])
    name = df_raw.iloc[:, i].name
    count = 0
    for item in attr:
        if not item==item:
            count = count+1
    if(count>del_rate*len(df_raw)):
        print(name)
        print("del")
        df_new = df_raw.drop(name, axis=1)

In [70]:
len(df_new.columns)

81